<?php 

$ESO_PLAYER_SKILLS14 = array (
	29665 => 
	array (
		    'name' => 'New Evocation 1',
		    'rank' => '1',
		    'learnedLevel' => '2',
		    'skillIndex' => '3',
		    'skillType' => '3',
		    'skillLine' => 'Light Armor',
		    'raceType' => '',
		    'classType' => '',
		    'prevSkill' => '0',
		    'nextSkill' => '45557',
		    'nextSkill2' => '-1',
		    'baseAbilityId' => '29665',
	),
	45557 =>
	array (
			'name' => 'New Evocation 2',
			'rank' => '2',
			'learnedLevel' => '18',
			'skillIndex' => '3',
			'skillType' => '3',
			'skillLine' => 'Light Armor',
			'raceType' => '',
			'classType' => '',
			'prevSkill' => '29665',
			'nextSkill' => '-1',
			'nextSkill2' => '-1',
			'baseAbilityId' => '29665',
	),
	29636 =>
	array (
			'name' => 'New Recovery 1',
			'rank' => '1',
			'learnedLevel' => '6',
			'skillIndex' => '2',
			'skillType' => '3',
			'skillLine' => 'Light Armor',
			'raceType' => '',
			'classType' => '',
			'prevSkill' => '0',
			'nextSkill' => '45548',
			'nextSkill2' => '-1',
			'baseAbilityId' => '29636',
	),
	45548 =>
	array (
			'name' => 'New Recovery 2',
			'rank' => '2',
			'learnedLevel' => '10',
			'skillIndex' => '2',
			'skillType' => '3',
			'skillLine' => 'Light Armor',
			'raceType' => '',
			'classType' => '',
			'prevSkill' => '29665',
			'nextSkill' => '45549',
			'nextSkill2' => '-1',
			'baseAbilityId' => '29636',
	),
	45549 =>
	array (
			'name' => 'New Recovery 3',
			'rank' => '2',
			'learnedLevel' => '30',
			'skillIndex' => '2',
			'skillType' => '3',
			'skillLine' => 'Light Armor',
			'raceType' => '',
			'classType' => '',
			'prevSkill' => '45548',
			'nextSkill' => '0',
			'nextSkill2' => '-1',
			'baseAbilityId' => '29636',
	),
);