$ESO_PLAYER_SKILLS = array (
  85876 => 
  array (
    'name' => 'Emerald Moss',
    'rank' => '1',
    'learnedLevel' => '22',
    'skillIndex' => '9',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '-1',
    'nextSkill' => '85877',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85876',
  ),
  85877 => 
  array (
    'name' => 'Emerald Moss',
    'rank' => '2',
    'learnedLevel' => '36',
    'skillIndex' => '9',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '858761',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85876',
  ),
  85878 => 
  array (
    'name' => 'Nature\'s Gift',
    'rank' => '1',
    'learnedLevel' => '14',
    'skillIndex' => '8',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '85879',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85878',
  ),
  85879 => 
  array (
    'name' => 'Nature\'s Gift',
    'rank' => '2',
    'learnedLevel' => '27',
    'skillIndex' => '8',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '85878',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85878',
  ),
  85880 => 
  array (
    'name' => 'Maturation',
    'rank' => '1',
    'learnedLevel' => '39',
    'skillIndex' => '10',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '85881',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85880',
  ),
  85881 => 
  array (
    'name' => 'Maturation',
    'rank' => '2',
    'learnedLevel' => '50',
    'skillIndex' => '10',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '85880',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85880',
  ),
  85882 => 
  array (
    'name' => 'Accelerated Growth',
    'rank' => '1',
    'learnedLevel' => '8',
    'skillIndex' => '7',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '85883',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85882',
  ),
  85883 => 
  array (
    'name' => 'Accelerated Growth',
    'rank' => '2',
    'learnedLevel' => '18',
    'skillIndex' => '7',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '85882',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85882',
  ),
   85982 => 
  array (
    'name' => 'Feral Guardian',
    'rank' => '1',
    'learnedLevel' => '0',
    'skillIndex' => '1',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '85983',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85982',
  ),
   85983 => 
  array (
    'name' => 'Feral Guardian',
    'rank' => '2',
    'learnedLevel' => '0',
    'skillIndex' => '1',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '85982',
    'nextSkill' => '85984',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85982',
  ),
   85984 => 
  array (
    'name' => 'Feral Guardian',
    'rank' => '3',
    'learnedLevel' => '0',
    'skillIndex' => '1',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '85983',
    'nextSkill' => '85985',
    'nextSkill2' => '-1',
    'baseAbilityId' => '85982',
  ),
  85985 => 
  array (
    'name' => 'Feral Guardian',
    'rank' => '4',
    'learnedLevel' => '0',
    'skillIndex' => '1',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '85984',
    'nextSkill' => '85986',
    'nextSkill2' => '85990',
    'baseAbilityId' => '85982',
  ),
  85998 => 
  array (
    'name' => 'Dive',
    'rank' => '4',
    'learnedLevel' => '1',
    'skillIndex' => '2',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '85997',
    'nextSkill' => '85999',
    'nextSkill2' => '86003',
    'baseAbilityId' => '0',
  ),
  86026 => 
  array (
    'name' => 'Swarm',
    'rank' => '4',
    'learnedLevel' => '20',
    'skillIndex' => '4',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86025',
    'nextSkill' => '86027',
    'nextSkill2' => '86031',
    'baseAbilityId' => '0',
  ),
  86040 => 
  array (
    'name' => 'Falcon\'s Swiftness',
    'rank' => '4',
    'learnedLevel' => '42',
    'skillIndex' => '6',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86039',
    'nextSkill' => '86041',
    'nextSkill2' => '86045',
    'baseAbilityId' => '0',
  ),
  86053 => 
  array (
    'name' => 'Betty Netch',
    'rank' => '4',
    'learnedLevel' => '30',
    'skillIndex' => '5',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86052',
    'nextSkill' => '86054',
    'nextSkill2' => '86058',
    'baseAbilityId' => '0',
  ),
  86062 => 
  array (
    'name' => 'Savage Beast',
    'rank' => '1',
    'learnedLevel' => '14',
    'skillIndex' => '8',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86063',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86062',
  ),
  86063 => 
  array (
    'name' => 'Savage Beast',
    'rank' => '2',
    'learnedLevel' => '27',
    'skillIndex' => '8',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86062',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86062',
  ),
  86064 => 
  array (
    'name' => 'Bond With Nature',
    'rank' => '1',
    'learnedLevel' => '8',
    'skillIndex' => '7',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86065',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86064',
  ),
  86065 => 
  array (
    'name' => 'Bond With Nature',
    'rank' => '2',
    'learnedLevel' => '18',
    'skillIndex' => '7',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86064',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86064',
  ),
  86066 => 
  array (
    'name' => 'Flourish',
    'rank' => '1',
    'learnedLevel' => '22',
    'skillIndex' => '9',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86067',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86066',
  ),
  86067 => 
  array (
    'name' => 'Flourish',
    'rank' => '2',
    'learnedLevel' => '36',
    'skillIndex' => '9',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86066',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86066',
  ),
  86068 => 
  array (
    'name' => 'Advanced Species',
    'rank' => '1',
    'learnedLevel' => '39',
    'skillIndex' => '10',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86069',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86068',
  ),
  86069 => 
  array (
    'name' => 'Advanced Species',
    'rank' => '2',
    'learnedLevel' => '50',
    'skillIndex' => '10',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86068',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86068',
  ),
  86112 => 
  array (
    'name' => 'Sleet Storm',
    'rank' => '4',
    'learnedLevel' => '12',
    'skillIndex' => '1',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86111',
    'nextSkill' => '86113',
    'nextSkill2' => '86117',
    'baseAbilityId' => '0',
  ),
  86125 => 
  array (
    'name' => 'Frost Cloak',
    'rank' => '4',
    'learnedLevel' => '1',
    'skillIndex' => '2',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86124',
    'nextSkill' => '86126',
    'nextSkill2' => '86130',
    'baseAbilityId' => '0',
  ),
  86138 => 
  array (
    'name' => 'Crystallized Shield',
    'rank' => '4',
    'learnedLevel' => '30',
    'skillIndex' => '5',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86137',
    'nextSkill' => '86139',
    'nextSkill2' => '86143',
    'baseAbilityId' => '0',
  ),
  86151 => 
  array (
    'name' => 'Arctic Wind',
    'rank' => '4',
    'learnedLevel' => '20',
    'skillIndex' => '4',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86150',
    'nextSkill' => '86152',
    'nextSkill2' => '86156',
    'baseAbilityId' => '0',
  ),
  86164 => 
  array (
    'name' => 'Impaling Shards',
    'rank' => '4',
    'learnedLevel' => '4',
    'skillIndex' => '3',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86163',
    'nextSkill' => '86165',
    'nextSkill2' => '86169',
    'baseAbilityId' => '0',
  ),
  86178 => 
  array (
    'name' => 'Frozen Gate',
    'rank' => '4',
    'learnedLevel' => '42',
    'skillIndex' => '6',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86177',
    'nextSkill' => '86179',
    'nextSkill2' => '86183',
    'baseAbilityId' => '0',
  ),
  86189 => 
  array (
    'name' => 'Frozen Armor',
    'rank' => '1',
    'learnedLevel' => '14',
    'skillIndex' => '8',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86190',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86189',
  ),
  86190 => 
  array (
    'name' => 'Frozen Armor',
    'rank' => '2',
    'learnedLevel' => '27',
    'skillIndex' => '8',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86189',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86189',
  ),
  86191 => 
  array (
    'name' => 'Glacial Presence',
    'rank' => '1',
    'learnedLevel' => '8',
    'skillIndex' => '7',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86192',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86191',
  ),
  86192 => 
  array (
    'name' => 'Glacial Presence',
    'rank' => '2',
    'learnedLevel' => '18',
    'skillIndex' => '7',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86191',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86191',
  ),
  86193 => 
  array (
    'name' => 'Icy Aura',
    'rank' => '1',
    'learnedLevel' => '22',
    'skillIndex' => '9',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86194',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86193',
  ),
  86194 => 
  array (
    'name' => 'Icy Aura',
    'rank' => '2',
    'learnedLevel' => '36',
    'skillIndex' => '9',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86193',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86193',
  ),
  86195 => 
  array (
    'name' => 'Piercing Cold',
    'rank' => '1',
    'learnedLevel' => '39',
    'skillIndex' => '10',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '0',
    'nextSkill' => '86196',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86195',
  ),
  86196 => 
  array (
    'name' => 'Piercing Cold',
    'rank' => '2',
    'learnedLevel' => '50',
    'skillIndex' => '10',
    'skillType' => '1',
    'skillLine' => 'Winter\'s Embrace',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86195',
    'nextSkill' => '0',
    'nextSkill2' => '-1',
    'baseAbilityId' => '86195',
  ),
  93593 => 
  array (
    'name' => 'Scorch',
    'rank' => '4',
    'learnedLevel' => '4',
    'skillIndex' => '3',
    'skillType' => '1',
    'skillLine' => 'Animal Companions',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '86013',
    'nextSkill' => '86019',
    'nextSkill2' => '86015',
    'baseAbilityId' => '0',
  ),
  93771 => 
  array (
    'name' => 'Fungal Growth',
    'rank' => '4',
    'learnedLevel' => '1',
    'skillIndex' => '2',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '93770',
    'nextSkill' => '85862',
    'nextSkill2' => '85863',
    'baseAbilityId' => '0',
  ),
  93804 => 
  array (
    'name' => 'Healing Seed',
    'rank' => '4',
    'learnedLevel' => '4',
    'skillIndex' => '3',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '93803',
    'nextSkill' => '85840',
    'nextSkill2' => '85845',
    'baseAbilityId' => '0',
  ),
  93877 => 
  array (
    'name' => 'Living Vines',
    'rank' => '4',
    'learnedLevel' => '20',
    'skillIndex' => '4',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '93876',
    'nextSkill' => '85850',
    'nextSkill2' => '85851',
    'baseAbilityId' => '0',
  ),
  93908 => 
  array (
    'name' => 'Lotus Flower',
    'rank' => '4',
    'learnedLevel' => '30',
    'skillIndex' => '5',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '93907',
    'nextSkill' => '85854',
    'nextSkill2' => '85855',
    'baseAbilityId' => '0',
  ),
  93934 => 
  array (
    'name' => 'Nature\'s Grasp',
    'rank' => '4',
    'learnedLevel' => '42',
    'skillIndex' => '6',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '93933',
    'nextSkill' => '85859',
    'nextSkill2' => '85858',
    'baseAbilityId' => '0',
  ),
  93968 => 
  array (
    'name' => 'Secluded Grove',
    'rank' => '4',
    'learnedLevel' => '12',
    'skillIndex' => '1',
    'skillType' => '1',
    'skillLine' => 'Green Balance',
    'raceType' => '',
    'classType' => 'Warden',
    'prevSkill' => '93967',
    'nextSkill' => '85804',
    'nextSkill2' => '85807',
    'baseAbilityId' => '0',
  ),
);